name: CD to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t devops-node-api:staging .

      - name: Push Docker image (optional)
        # nanti bisa push ke Docker Hub / GitHub Container Registry
        run: echo "Push to registry here if needed"

      - name: Deploy to staging server (optional)
        run: echo "Deploy steps here (SSH, Docker Compose up etc)"

