name: Build and Push Docker Image

on:
  push:
    branches:
    - dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: BUILD DOCKER IMAGE
      run: docker build -t paulkusuma/devops-node-api:latest .

    - name: PUSH DOCKER IMAGE
      run: docker push paulkusuma/devops-node-api:latest

